# .travis.yml 文件

# 声明构建语言环境
language: android
android:        # 配置信息
  components:
    # 你可能需要修改下面两项的版本
    - build-tools-29.0.2
    - android-28
    # Android Support Repository
    - extra-android-m2repository
    # Support Library
    - extra-android-support
script:
  # 生成 APK
  - ./gradlew assembleRelease

# 部署
deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  # Github oauth token
  api_key: "$GIT_TOKEN"
  file:
    - app/build/outputs/apk/release/app-release.apk
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: true
  # 发布时机
  on:
    # tags设置为true表示只有在有tag的情况下才部署
    tags: true
    all_branches: true
